apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  namespace: demo
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app123  # put your real password here
  POSTGRES_DB: usersdb