apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  namespace: demo
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  POSTGRES_USER: YXBwCg==
  POSTGRES_PASSWORD: YXBwMTIzCg==
  POSTGRES_DB: dXNlcnNkYgo=