apiVersion: v1
kind: Namespace
metadata: 
  name: demo
spec:

# kubectl apply create-namespace.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: "demo-app-pod"
  namespace: demo
  labels:
    app: "demo-app"
spec:
  containers:
  - name: demo-app-container
    image: docker.io/jpalaparthi/omnenext-demo:v2
    # add under spec.template.spec.containers[*].env
    env:
      - name: POD_NAME
        valueFrom: { fieldRef: { fieldPath: metadata.name } }
      - name: POD_NAMESPACE
        valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
      - name: POD_UID
        valueFrom: { fieldRef: { fieldPath: metadata.uid } }
      - name: POD_IP
        valueFrom: { fieldRef: { fieldPath: status.podIP } }
      - name: NODE_NAME
        valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  8080
      name:  http

--- 
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
spec:
  selector:
    app: "demo-app"
  type: LoadBalancer
  ports:
  - name: demo-app
    protocol: TCP
    port: 8081
    targetPort: 8080
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    #nodePort: 