// Code generated by MockGen. DO NOT EDIT.
// Source: userhandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	messaging "users-service/messaging"

	fiber "github.com/gofiber/fiber/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockIUserHandler is a mock of IUserHandler interface.
type MockIUserHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIUserHandlerMockRecorder
}

// MockIUserHandlerMockRecorder is the mock recorder for MockIUserHandler.
type MockIUserHandlerMockRecorder struct {
	mock *MockIUserHandler
}

// NewMockIUserHandler creates a new mock instance.
func NewMockIUserHandler(ctrl *gomock.Controller) *MockIUserHandler {
	mock := &MockIUserHandler{ctrl: ctrl}
	mock.recorder = &MockIUserHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserHandler) EXPECT() *MockIUserHandlerMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockIUserHandler) CreateOrder(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockIUserHandlerMockRecorder) CreateOrder(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockIUserHandler)(nil).CreateOrder), c)
}

// CreateUser mocks base method.
func (m *MockIUserHandler) CreateUser(msg *messaging.Messaging) func(*fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", msg)
	ret0, _ := ret[0].(func(*fiber.Ctx) error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserHandlerMockRecorder) CreateUser(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserHandler)(nil).CreateUser), msg)
}

// GetUserBy mocks base method.
func (m *MockIUserHandler) GetUserBy(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBy", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUserBy indicates an expected call of GetUserBy.
func (mr *MockIUserHandlerMockRecorder) GetUserBy(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBy", reflect.TypeOf((*MockIUserHandler)(nil).GetUserBy), c)
}

// GetUsersByLimit mocks base method.
func (m *MockIUserHandler) GetUsersByLimit(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByLimit", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUsersByLimit indicates an expected call of GetUsersByLimit.
func (mr *MockIUserHandlerMockRecorder) GetUsersByLimit(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByLimit", reflect.TypeOf((*MockIUserHandler)(nil).GetUsersByLimit), c)
}
