// Code generated by MockGen. DO NOT EDIT.
// Source: userdb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "users-service/models"

	gomock "github.com/golang/mock/gomock"
)

// MockIUserDB is a mock of IUserDB interface.
type MockIUserDB struct {
	ctrl     *gomock.Controller
	recorder *MockIUserDBMockRecorder
}

// MockIUserDBMockRecorder is the mock recorder for MockIUserDB.
type MockIUserDBMockRecorder struct {
	mock *MockIUserDB
}

// NewMockIUserDB creates a new mock instance.
func NewMockIUserDB(ctrl *gomock.Controller) *MockIUserDB {
	mock := &MockIUserDB{ctrl: ctrl}
	mock.recorder = &MockIUserDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserDB) EXPECT() *MockIUserDBMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUserDB) Create(user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIUserDBMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserDB)(nil).Create), user)
}

// CreateOrder mocks base method.
func (m *MockIUserDB) CreateOrder(order *models.Order) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", order)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockIUserDBMockRecorder) CreateOrder(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockIUserDB)(nil).CreateOrder), order)
}

// GetBy mocks base method.
func (m *MockIUserDB) GetBy(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBy", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBy indicates an expected call of GetBy.
func (mr *MockIUserDBMockRecorder) GetBy(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBy", reflect.TypeOf((*MockIUserDB)(nil).GetBy), id)
}

// GetByLimit mocks base method.
func (m *MockIUserDB) GetByLimit(limit, offset int) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLimit", limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLimit indicates an expected call of GetByLimit.
func (mr *MockIUserDBMockRecorder) GetByLimit(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLimit", reflect.TypeOf((*MockIUserDB)(nil).GetByLimit), limit, offset)
}
